[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pd2-filter-generator"
version = "0.0.0"
description = 'Project Diablo2 Filter Generator'
readme = "README.md"
requires-python = ">=3.9"

[dependency-groups]
dev = [
    "pytest",
    "click",
    "pystache",
]

[tool.hatch.envs.default]
dependency-groups = [
  "dev",
]

[tool.hatch.envs.types]
dependencies = [
  "mypy~=1.20.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src}"

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14"]


[tool.ruff.lint]
ignore = ["TRY003", "EM102"]
