"""
Generated UniqueItem enum from PD2 data.

DO NOT EDIT MANUALLY - regenerate with: hatch run ./scripts/generate.py generate
"""

from __future__ import annotations

from pd2_filter_generator.expression import BoolRef


class _UniqueItem(BoolRef):
    """Item type metadata."""

    # TODO: ladder is always False
    def __init__(self, value: str, ladder: bool, lvl: int, lvl_req: int):  # noqa: FBT001
        super().__init__(value)
        self._ladder = ladder
        self._lvl = lvl
        self._lvl_req = lvl_req

    @property
    def ladder(self) -> bool:
        return self._ladder

    @property
    def lvl(self) -> int:
        return self._lvl

    @property
    def lvl_req(self) -> int:
        return self._lvl_req


values = [
    THE_GNASHER := _UniqueItem(
        value="hax",
        ladder=False,
        lvl=7,
        lvl_req=5,
    ),
    DEATHSPADE := _UniqueItem(
        value="axe",
        ladder=False,
        lvl=12,
        lvl_req=9,
    ),
    BLADEBONE := _UniqueItem(
        value="2ax",
        ladder=False,
        lvl=20,
        lvl_req=15,
    ),
    SKULL_SPLITTER := _UniqueItem(
        value="mpi",
        ladder=False,
        lvl=28,
        lvl_req=21,
    ),
    RAKESCAR := _UniqueItem(
        value="wax",
        ladder=False,
        lvl=36,
        lvl_req=27,
    ),
    AXE_OF_FECHMAR := _UniqueItem(
        value="lax",
        ladder=False,
        lvl=11,
        lvl_req=8,
    ),
    GORESHOVEL := _UniqueItem(
        value="bax",
        ladder=False,
        lvl=19,
        lvl_req=14,
    ),
    THE_CHIEFTAIN := _UniqueItem(
        value="btx",
        ladder=False,
        lvl=26,
        lvl_req=19,
    ),
    BRAINHEW := _UniqueItem(
        value="gax",
        ladder=False,
        lvl=34,
        lvl_req=25,
    ),
    HUMONGOUS := _UniqueItem(
        value="gix",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    TORCH_OF_IRO := _UniqueItem(
        value="wnd",
        ladder=False,
        lvl=7,
        lvl_req=5,
    ),
    MAELSTROM := _UniqueItem(
        value="ywn",
        ladder=False,
        lvl=19,
        lvl_req=14,
    ),
    GRAVENSPINE := _UniqueItem(
        value="bwn",
        ladder=False,
        lvl=27,
        lvl_req=20,
    ),
    UMES_LAMENT := _UniqueItem(
        value="gwn",
        ladder=False,
        lvl=38,
        lvl_req=28,
    ),
    FELLOAK := _UniqueItem(
        value="clb",
        ladder=False,
        lvl=4,
        lvl_req=3,
    ),
    KNELL_STRIKER := _UniqueItem(
        value="scp",
        ladder=False,
        lvl=7,
        lvl_req=5,
    ),
    RUSTHANDLE := _UniqueItem(
        value="gsc",
        ladder=False,
        lvl=23,
        lvl_req=17,
    ),
    STORMEYE := _UniqueItem(
        value="wsp",
        ladder=False,
        lvl=31,
        lvl_req=23,
    ),
    STOUTNAIL := _UniqueItem(
        value="spc",
        ladder=False,
        lvl=7,
        lvl_req=5,
    ),
    CRUSHFLANGE := _UniqueItem(
        value="mac",
        ladder=False,
        lvl=12,
        lvl_req=9,
    ),
    BLOODRISE := _UniqueItem(
        value="mst",
        ladder=False,
        lvl=20,
        lvl_req=15,
    ),
    THE_GENERALS_TAN_DO_LI_GA := _UniqueItem(
        value="fla",
        ladder=False,
        lvl=28,
        lvl_req=21,
    ),
    IRONSTONE := _UniqueItem(
        value="whm",
        ladder=False,
        lvl=36,
        lvl_req=27,
    ),
    BONESNAP := _UniqueItem(
        value="mau",
        ladder=False,
        lvl=32,
        lvl_req=24,
    ),
    STEELDRIVER := _UniqueItem(
        value="gma",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    RIXOTS_KEEN := _UniqueItem(
        value="ssd",
        ladder=False,
        lvl=3,
        lvl_req=2,
    ),
    BLOOD_CRESCENT := _UniqueItem(
        value="scm",
        ladder=False,
        lvl=10,
        lvl_req=7,
    ),
    SKEWER_OF_KRINTIZ := _UniqueItem(
        value="sbr",
        ladder=False,
        lvl=14,
        lvl_req=10,
    ),
    GLEAMSCYTHE := _UniqueItem(
        value="flc",
        ladder=False,
        lvl=18,
        lvl_req=13,
    ),
    GRISWOLDS_EDGE := _UniqueItem(
        value="bsd",
        ladder=False,
        lvl=23,
        lvl_req=17,
    ),
    HELLPLAGUE := _UniqueItem(
        value="lsd",
        ladder=False,
        lvl=30,
        lvl_req=22,
    ),
    CULWENS_POINT := _UniqueItem(
        value="wsd",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    SHADOWFANG := _UniqueItem(
        value="2hs",
        ladder=False,
        lvl=16,
        lvl_req=12,
    ),
    SOULFLAY := _UniqueItem(
        value="clm",
        ladder=False,
        lvl=26,
        lvl_req=19,
    ),
    KINEMILS_AWL := _UniqueItem(
        value="gis",
        ladder=False,
        lvl=31,
        lvl_req=23,
    ),
    BLACKTONGUE := _UniqueItem(
        value="bsw",
        ladder=False,
        lvl=35,
        lvl_req=26,
    ),
    RIPSAW := _UniqueItem(
        value="flb",
        ladder=False,
        lvl=35,
        lvl_req=26,
    ),
    THE_PATRIARCH := _UniqueItem(
        value="gsd",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    GULL := _UniqueItem(
        value="dgr",
        ladder=False,
        lvl=6,
        lvl_req=4,
    ),
    THE_DIGGLER := _UniqueItem(
        value="dir",
        ladder=False,
        lvl=15,
        lvl_req=11,
    ),
    THE_JADE_TAN_DO := _UniqueItem(
        value="kri",
        ladder=False,
        lvl=26,
        lvl_req=19,
    ),
    SPECTRAL_SHARD := _UniqueItem(
        value="bld",
        ladder=False,
        lvl=34,
        lvl_req=25,
    ),
    THE_DRAGON_CHANG := _UniqueItem(
        value="spr",
        ladder=False,
        lvl=11,
        lvl_req=8,
    ),
    RAZORTINE := _UniqueItem(
        value="tri",
        ladder=False,
        lvl=16,
        lvl_req=12,
    ),
    BLOODTHIEF := _UniqueItem(
        value="brn",
        ladder=False,
        lvl=23,
        lvl_req=17,
    ),
    LANCE_OF_YAGGAI := _UniqueItem(
        value="spt",
        ladder=False,
        lvl=30,
        lvl_req=22,
    ),
    THE_TANNR_GOREROD := _UniqueItem(
        value="pik",
        ladder=False,
        lvl=36,
        lvl_req=27,
    ),
    DIMOAKS_HEW := _UniqueItem(
        value="bar",
        ladder=False,
        lvl=11,
        lvl_req=8,
    ),
    STEELGOAD := _UniqueItem(
        value="vou",
        ladder=False,
        lvl=19,
        lvl_req=14,
    ),
    SOUL_HARVEST := _UniqueItem(
        value="scy",
        ladder=False,
        lvl=26,
        lvl_req=19,
    ),
    THE_BATTLEBRANCH := _UniqueItem(
        value="pax",
        ladder=False,
        lvl=34,
        lvl_req=25,
    ),
    WOESTAVE := _UniqueItem(
        value="hal",
        ladder=False,
        lvl=38,
        lvl_req=28,
    ),
    THE_GRIM_REAPER := _UniqueItem(
        value="wsc",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    BANE_ASH := _UniqueItem(
        value="sst",
        ladder=False,
        lvl=7,
        lvl_req=5,
    ),
    SERPENT_LORD := _UniqueItem(
        value="lst",
        ladder=False,
        lvl=12,
        lvl_req=9,
    ),
    SPIRE_OF_LAZARUS := _UniqueItem(
        value="cst",
        ladder=False,
        lvl=24,
        lvl_req=18,
    ),
    THE_SALAMANDER := _UniqueItem(
        value="bst",
        ladder=False,
        lvl=28,
        lvl_req=21,
    ),
    THE_IRON_JANG_BONG := _UniqueItem(
        value="wst",
        ladder=False,
        lvl=38,
        lvl_req=28,
    ),
    PLUCKEYE := _UniqueItem(
        value="sbw",
        ladder=False,
        lvl=10,
        lvl_req=7,
    ),
    WITHERSTRING := _UniqueItem(
        value="hbw",
        ladder=False,
        lvl=18,
        lvl_req=13,
    ),
    RAVEN_CLAW := _UniqueItem(
        value="lbw",
        ladder=False,
        lvl=20,
        lvl_req=15,
    ),
    ROGUES_BOW := _UniqueItem(
        value="cbw",
        ladder=False,
        lvl=27,
        lvl_req=20,
    ),
    STORMSTRIKE := _UniqueItem(
        value="sbb",
        ladder=False,
        lvl=34,
        lvl_req=25,
    ),
    WIZENDRAW := _UniqueItem(
        value="lbb",
        ladder=False,
        lvl=35,
        lvl_req=26,
    ),
    HELLCLAP := _UniqueItem(
        value="swb",
        ladder=False,
        lvl=36,
        lvl_req=27,
    ),
    BLASTBARK := _UniqueItem(
        value="lwb",
        ladder=False,
        lvl=38,
        lvl_req=28,
    ),
    LEADCROW := _UniqueItem(
        value="lxb",
        ladder=False,
        lvl=12,
        lvl_req=9,
    ),
    ICHORSTING := _UniqueItem(
        value="mxb",
        ladder=False,
        lvl=24,
        lvl_req=18,
    ),
    HELLCAST := _UniqueItem(
        value="hxb",
        ladder=False,
        lvl=36,
        lvl_req=27,
    ),
    DOOMSLINGER := _UniqueItem(
        value="rxb",
        ladder=False,
        lvl=38,
        lvl_req=28,
    ),
    BIGGINS_BONNET := _UniqueItem(
        value="cap",
        ladder=False,
        lvl=4,
        lvl_req=3,
    ),
    TARNHELM := _UniqueItem(
        value="skp",
        ladder=False,
        lvl=20,
        lvl_req=15,
    ),
    COIF_OF_GLORY := _UniqueItem(
        value="hlm",
        ladder=False,
        lvl=19,
        lvl_req=14,
    ),
    DUSKDEEP := _UniqueItem(
        value="fhl",
        ladder=False,
        lvl=23,
        lvl_req=17,
    ),
    WORMSKULL := _UniqueItem(
        value="bhm",
        ladder=False,
        lvl=28,
        lvl_req=21,
    ),
    HOWLTUSK := _UniqueItem(
        value="ghm",
        ladder=False,
        lvl=34,
        lvl_req=25,
    ),
    UNDEAD_CROWN := _UniqueItem(
        value="crn",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    THE_FACE_OF_HORROR := _UniqueItem(
        value="msk",
        ladder=False,
        lvl=27,
        lvl_req=20,
    ),
    GREYFORM := _UniqueItem(
        value="qui",
        ladder=False,
        lvl=10,
        lvl_req=7,
    ),
    BLINKBATS_FORM := _UniqueItem(
        value="lea",
        ladder=False,
        lvl=16,
        lvl_req=12,
    ),
    THE_CENTURION := _UniqueItem(
        value="hla",
        ladder=False,
        lvl=19,
        lvl_req=14,
    ),
    TWITCHTHROE := _UniqueItem(
        value="stu",
        ladder=False,
        lvl=22,
        lvl_req=16,
    ),
    DARKGLOW := _UniqueItem(
        value="rng",
        ladder=False,
        lvl=19,
        lvl_req=14,
    ),
    HAWKMAIL := _UniqueItem(
        value="scl",
        ladder=False,
        lvl=20,
        lvl_req=15,
    ),
    SPARKING_MAIL := _UniqueItem(
        value="chn",
        ladder=False,
        lvl=23,
        lvl_req=17,
    ),
    VENOM_WARD := _UniqueItem(
        value="brs",
        ladder=False,
        lvl=27,
        lvl_req=20,
    ),
    ICEBLINK := _UniqueItem(
        value="spl",
        ladder=False,
        lvl=30,
        lvl_req=22,
    ),
    BONEFLESH := _UniqueItem(
        value="plt",
        ladder=False,
        lvl=35,
        lvl_req=26,
    ),
    ROCKFLEECE := _UniqueItem(
        value="fld",
        ladder=False,
        lvl=38,
        lvl_req=28,
    ),
    RATTLECAGE := _UniqueItem(
        value="gth",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    GOLDSKIN := _UniqueItem(
        value="ful",
        ladder=False,
        lvl=38,
        lvl_req=28,
    ),
    SILKS_OF_THE_VICTOR := _UniqueItem(
        value="aar",
        ladder=False,
        lvl=38,
        lvl_req=28,
    ),
    HEAVENLY_GARB := _UniqueItem(
        value="ltp",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    PELTA_LUNATA := _UniqueItem(
        value="buc",
        ladder=False,
        lvl=3,
        lvl_req=2,
    ),
    UMBRAL_DISK := _UniqueItem(
        value="sml",
        ladder=False,
        lvl=12,
        lvl_req=9,
    ),
    STORMGUILD := _UniqueItem(
        value="lrg",
        ladder=False,
        lvl=18,
        lvl_req=13,
    ),
    WALL_OF_THE_EYELESS := _UniqueItem(
        value="bsh",
        ladder=False,
        lvl=27,
        lvl_req=20,
    ),
    SWORDBACK_HOLD := _UniqueItem(
        value="spk",
        ladder=False,
        lvl=20,
        lvl_req=15,
    ),
    STEELCLASH := _UniqueItem(
        value="kit",
        ladder=False,
        lvl=23,
        lvl_req=17,
    ),
    BVERRIT_KEEP := _UniqueItem(
        value="tow",
        ladder=False,
        lvl=26,
        lvl_req=19,
    ),
    THE_WARD := _UniqueItem(
        value="gts",
        ladder=False,
        lvl=35,
        lvl_req=26,
    ),
    THE_HAND_OF_BROC := _UniqueItem(
        value="lgl",
        ladder=False,
        lvl=7,
        lvl_req=5,
    ),
    BLOODFIST := _UniqueItem(
        value="vgl",
        ladder=False,
        lvl=12,
        lvl_req=9,
    ),
    CHANCE_GUARDS := _UniqueItem(
        value="mgl",
        ladder=False,
        lvl=20,
        lvl_req=15,
    ),
    MAGEFIST := _UniqueItem(
        value="tgl",
        ladder=False,
        lvl=31,
        lvl_req=23,
    ),
    FROSTBURN := _UniqueItem(
        value="hgl",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    HOTSPUR := _UniqueItem(
        value="lbt",
        ladder=False,
        lvl=7,
        lvl_req=5,
    ),
    GOREFOOT := _UniqueItem(
        value="vbt",
        ladder=False,
        lvl=12,
        lvl_req=12,
    ),
    TREADS_OF_CTHON := _UniqueItem(
        value="mbt",
        ladder=False,
        lvl=20,
        lvl_req=15,
    ),
    GOBLIN_TOE := _UniqueItem(
        value="tbt",
        ladder=False,
        lvl=30,
        lvl_req=22,
    ),
    TEARHAUNCH := _UniqueItem(
        value="hbt",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    LENYMO := _UniqueItem(
        value="lbl",
        ladder=False,
        lvl=10,
        lvl_req=7,
    ),
    SNAKECORD := _UniqueItem(
        value="vbl",
        ladder=False,
        lvl=16,
        lvl_req=12,
    ),
    NIGHTSMOKE := _UniqueItem(
        value="mbl",
        ladder=False,
        lvl=27,
        lvl_req=20,
    ),
    GOLDWRAP := _UniqueItem(
        value="tbl",
        ladder=False,
        lvl=36,
        lvl_req=27,
    ),
    BLADEBUCKLE := _UniqueItem(
        value="hbl",
        ladder=False,
        lvl=39,
        lvl_req=39,
    ),
    NOKOZAN_RELIC := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=14,
        lvl_req=10,
    ),
    THE_EYE_OF_ETLICH := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=20,
        lvl_req=15,
    ),
    THE_MAHIM_OAK_CURIO := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=34,
        lvl_req=25,
    ),
    NAGELRING := _UniqueItem(
        value="rin",
        ladder=False,
        lvl=10,
        lvl_req=7,
    ),
    MANALD_HEAL := _UniqueItem(
        value="rin",
        ladder=False,
        lvl=20,
        lvl_req=15,
    ),
    THE_STONE_OF_JORDAN := _UniqueItem(
        value="rin",
        ladder=False,
        lvl=39,
        lvl_req=29,
    ),
    AMULET_OF_THE_VIPER := _UniqueItem(
        value="vip",
        ladder=False,
        lvl=0,
        lvl_req=0,
    ),
    STAFF_OF_KINGS := _UniqueItem(
        value="msf",
        ladder=False,
        lvl=0,
        lvl_req=0,
    ),
    HORADRIC_STAFF := _UniqueItem(
        value="hst",
        ladder=False,
        lvl=0,
        lvl_req=0,
    ),
    HELL_FORGE_HAMMER := _UniqueItem(
        value="hfh",
        ladder=False,
        lvl=0,
        lvl_req=0,
    ),
    KHALIMS_FLAIL := _UniqueItem(
        value="qf1",
        ladder=False,
        lvl=0,
        lvl_req=0,
    ),
    KHALIMS_WILL := _UniqueItem(
        value="qf2",
        ladder=False,
        lvl=0,
        lvl_req=0,
    ),
    COLDKILL := _UniqueItem(
        value="9ha",
        ladder=False,
        lvl=44,
        lvl_req=36,
    ),
    BUTCHERS_PUPIL := _UniqueItem(
        value="9ax",
        ladder=False,
        lvl=47,
        lvl_req=39,
    ),
    ISLESTRIKE := _UniqueItem(
        value="92a",
        ladder=False,
        lvl=51,
        lvl_req=43,
    ),
    POMPEIIS_WRATH := _UniqueItem(
        value="9mp",
        ladder=False,
        lvl=53,
        lvl_req=45,
    ),
    GUARDIAN_NAGA := _UniqueItem(
        value="9wa",
        ladder=False,
        lvl=56,
        lvl_req=48,
    ),
    WARLORDS_TRUST := _UniqueItem(
        value="9la",
        ladder=False,
        lvl=43,
        lvl_req=35,
    ),
    SPELLSTEEL := _UniqueItem(
        value="9ba",
        ladder=False,
        lvl=47,
        lvl_req=39,
    ),
    STORMRIDER := _UniqueItem(
        value="9bt",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    BONESLAYER_BLADE := _UniqueItem(
        value="9ga",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    THE_MINOTAUR := _UniqueItem(
        value="9gi",
        ladder=False,
        lvl=53,
        lvl_req=45,
    ),
    SUICIDE_BRANCH := _UniqueItem(
        value="9wn",
        ladder=False,
        lvl=41,
        lvl_req=33,
    ),
    CARIN_SHARD := _UniqueItem(
        value="9yw",
        ladder=False,
        lvl=43,
        lvl_req=35,
    ),
    ARM_OF_KING_LEORIC := _UniqueItem(
        value="9bw",
        ladder=False,
        lvl=44,
        lvl_req=36,
    ),
    BLACKHAND_KEY := _UniqueItem(
        value="9gw",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    DARK_CLAN_CRUSHER := _UniqueItem(
        value="9cl",
        ladder=False,
        lvl=42,
        lvl_req=34,
    ),
    ZAKARUMS_HAND := _UniqueItem(
        value="9sc",
        ladder=False,
        lvl=45,
        lvl_req=37,
    ),
    THE_FETID_SPRINKLER := _UniqueItem(
        value="9qs",
        ladder=False,
        lvl=46,
        lvl_req=38,
    ),
    HAND_OF_BLESSED_LIGHT := _UniqueItem(
        value="9ws",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    FLESHRENDER := _UniqueItem(
        value="9sp",
        ladder=False,
        lvl=46,
        lvl_req=38,
    ),
    SURESHRILL_FROST := _UniqueItem(
        value="9ma",
        ladder=False,
        lvl=47,
        lvl_req=39,
    ),
    MOONFALL := _UniqueItem(
        value="9mt",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    BAEZILS_VORTEX := _UniqueItem(
        value="9fl",
        ladder=False,
        lvl=53,
        lvl_req=45,
    ),
    EARTHSHAKER := _UniqueItem(
        value="9wh",
        ladder=False,
        lvl=51,
        lvl_req=43,
    ),
    BLOODTREE_STUMP := _UniqueItem(
        value="9m9",
        ladder=False,
        lvl=56,
        lvl_req=48,
    ),
    THE_GAVEL_OF_PAIN := _UniqueItem(
        value="9gm",
        ladder=False,
        lvl=53,
        lvl_req=45,
    ),
    BLOODLETTER := _UniqueItem(
        value="9ss",
        ladder=False,
        lvl=38,
        lvl_req=30,
    ),
    COLDSTEEL_EYE := _UniqueItem(
        value="9sm",
        ladder=False,
        lvl=39,
        lvl_req=31,
    ),
    HEXFIRE := _UniqueItem(
        value="9sb",
        ladder=False,
        lvl=41,
        lvl_req=33,
    ),
    BLADE_OF_ALI_BABA := _UniqueItem(
        value="9fc",
        ladder=False,
        lvl=43,
        lvl_req=35,
    ),
    GINTHERS_RIFT := _UniqueItem(
        value="9cr",
        ladder=False,
        lvl=45,
        lvl_req=37,
    ),
    HEADSTRIKER := _UniqueItem(
        value="9bs",
        ladder=False,
        lvl=47,
        lvl_req=39,
    ),
    PLAGUE_BEARER := _UniqueItem(
        value="9ls",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    THE_ATLANTEAN := _UniqueItem(
        value="9wd",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    CRAINTE_VOMIR := _UniqueItem(
        value="92h",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    BING_SZ_WANG := _UniqueItem(
        value="9cm",
        ladder=False,
        lvl=51,
        lvl_req=43,
    ),
    THE_VILE_HUSK := _UniqueItem(
        value="9gs",
        ladder=False,
        lvl=52,
        lvl_req=44,
    ),
    CLOUDCRACK := _UniqueItem(
        value="9b9",
        ladder=False,
        lvl=53,
        lvl_req=45,
    ),
    TODESFAELLE_FLAMME := _UniqueItem(
        value="9fb",
        ladder=False,
        lvl=54,
        lvl_req=46,
    ),
    SWORDGUARD := _UniqueItem(
        value="9gd",
        ladder=False,
        lvl=55,
        lvl_req=48,
    ),
    SPINERIPPER := _UniqueItem(
        value="9dg",
        ladder=False,
        lvl=40,
        lvl_req=32,
    ),
    HEART_CARVER := _UniqueItem(
        value="9di",
        ladder=False,
        lvl=44,
        lvl_req=36,
    ),
    BLACKBOGS_SHARP := _UniqueItem(
        value="9kr",
        ladder=False,
        lvl=46,
        lvl_req=38,
    ),
    STORMSPIKE := _UniqueItem(
        value="9bl",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    THE_IMPALER := _UniqueItem(
        value="9sr",
        ladder=False,
        lvl=39,
        lvl_req=31,
    ),
    KELPIE_SNARE := _UniqueItem(
        value="9tr",
        ladder=False,
        lvl=41,
        lvl_req=33,
    ),
    SOULFEAST_TINE := _UniqueItem(
        value="9br",
        ladder=False,
        lvl=43,
        lvl_req=35,
    ),
    HONE_SUNDAN := _UniqueItem(
        value="9st",
        ladder=False,
        lvl=45,
        lvl_req=37,
    ),
    SPIRE_OF_HONOR := _UniqueItem(
        value="9p9",
        ladder=False,
        lvl=47,
        lvl_req=39,
    ),
    THE_MEAT_SCRAPER := _UniqueItem(
        value="9b7",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    BLACKLEACH_BLADE := _UniqueItem(
        value="9vo",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    ATHENAS_WRATH := _UniqueItem(
        value="9s8",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    PIERRE_TOMBALE_COUANT := _UniqueItem(
        value="9pa",
        ladder=False,
        lvl=51,
        lvl_req=43,
    ),
    HUSOLDAL_EVO := _UniqueItem(
        value="9h9",
        ladder=False,
        lvl=52,
        lvl_req=44,
    ),
    GRIMS_BURNING_DEAD := _UniqueItem(
        value="9wc",
        ladder=False,
        lvl=52,
        lvl_req=45,
    ),
    RAZORSWITCH := _UniqueItem(
        value="8ss",
        ladder=False,
        lvl=36,
        lvl_req=28,
    ),
    RIBCRACKER := _UniqueItem(
        value="8ls",
        ladder=False,
        lvl=39,
        lvl_req=31,
    ),
    CHROMATIC_IRE := _UniqueItem(
        value="8cs",
        ladder=False,
        lvl=43,
        lvl_req=35,
    ),
    WARPSPEAR := _UniqueItem(
        value="8bs",
        ladder=False,
        lvl=47,
        lvl_req=39,
    ),
    SKULL_COLLECTOR := _UniqueItem(
        value="8ws",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    SKYSTRIKE := _UniqueItem(
        value="8sb",
        ladder=False,
        lvl=36,
        lvl_req=28,
    ),
    RIPHOOK := _UniqueItem(
        value="8hb",
        ladder=False,
        lvl=39,
        lvl_req=31,
    ),
    KUKO_SHAKAKU := _UniqueItem(
        value="8lb",
        ladder=False,
        lvl=41,
        lvl_req=33,
    ),
    ENDLESSHAIL := _UniqueItem(
        value="8cb",
        ladder=False,
        lvl=44,
        lvl_req=36,
    ),
    WITCHWILD_STRING := _UniqueItem(
        value="8s8",
        ladder=False,
        lvl=47,
        lvl_req=39,
    ),
    CLIFFKILLER := _UniqueItem(
        value="8l8",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    MAGEWRATH := _UniqueItem(
        value="8sw",
        ladder=False,
        lvl=51,
        lvl_req=43,
    ),
    GOLDSTRIKE_ARCH := _UniqueItem(
        value="8lw",
        ladder=False,
        lvl=54,
        lvl_req=46,
    ),
    LANGER_BRISER := _UniqueItem(
        value="8lx",
        ladder=False,
        lvl=40,
        lvl_req=32,
    ),
    PUS_SPITTER := _UniqueItem(
        value="8mx",
        ladder=False,
        lvl=44,
        lvl_req=36,
    ),
    BURIZA_DO_KYANON := _UniqueItem(
        value="8hx",
        ladder=False,
        lvl=59,
        lvl_req=41,
    ),
    DEMON_MACHINE := _UniqueItem(
        value="8rx",
        ladder=False,
        lvl=57,
        lvl_req=49,
    ),
    PEASANT_CROWN := _UniqueItem(
        value="xap",
        ladder=False,
        lvl=36,
        lvl_req=28,
    ),
    ROCKSTOPPER := _UniqueItem(
        value="xkp",
        ladder=False,
        lvl=39,
        lvl_req=31,
    ),
    STEALSKULL := _UniqueItem(
        value="xlm",
        ladder=False,
        lvl=43,
        lvl_req=35,
    ),
    DARKSIGHT_HELM := _UniqueItem(
        value="xhl",
        ladder=False,
        lvl=46,
        lvl_req=38,
    ),
    VALKYRIE_WING := _UniqueItem(
        value="xhm",
        ladder=False,
        lvl=52,
        lvl_req=44,
    ),
    CROWN_OF_THIEVES := _UniqueItem(
        value="xrn",
        ladder=False,
        lvl=57,
        lvl_req=49,
    ),
    BLACKHORNS_FACE := _UniqueItem(
        value="xsk",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    VAMPIRE_GAZE := _UniqueItem(
        value="xh9",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    THE_SPIRIT_SHROUD := _UniqueItem(
        value="xui",
        ladder=False,
        lvl=36,
        lvl_req=28,
    ),
    SKIN_OF_THE_VIPERMAGI := _UniqueItem(
        value="xea",
        ladder=False,
        lvl=37,
        lvl_req=29,
    ),
    SKIN_OF_THE_FLAYED_ONE := _UniqueItem(
        value="xla",
        ladder=False,
        lvl=39,
        lvl_req=31,
    ),
    IRON_PELT := _UniqueItem(
        value="xtu",
        ladder=False,
        lvl=41,
        lvl_req=33,
    ),
    SPIRIT_FORGE := _UniqueItem(
        value="xng",
        ladder=False,
        lvl=43,
        lvl_req=35,
    ),
    CROW_CAW := _UniqueItem(
        value="xcl",
        ladder=False,
        lvl=45,
        lvl_req=37,
    ),
    SHAFTSTOP := _UniqueItem(
        value="xhn",
        ladder=False,
        lvl=46,
        lvl_req=38,
    ),
    DURIELS_SHELL := _UniqueItem(
        value="xrs",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    SKULLDERS_IRE := _UniqueItem(
        value="xpl",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    GUARDIAN_ANGEL := _UniqueItem(
        value="xlt",
        ladder=False,
        lvl=53,
        lvl_req=45,
    ),
    TOOTHROW := _UniqueItem(
        value="xld",
        ladder=False,
        lvl=56,
        lvl_req=48,
    ),
    ATMAS_WAIL := _UniqueItem(
        value="xth",
        ladder=False,
        lvl=59,
        lvl_req=51,
    ),
    BLACK_HADES := _UniqueItem(
        value="xul",
        ladder=False,
        lvl=61,
        lvl_req=53,
    ),
    CORPSEMOURN := _UniqueItem(
        value="xar",
        ladder=False,
        lvl=63,
        lvl_req=55,
    ),
    QUE_HEGANS_WISDOM := _UniqueItem(
        value="xtp",
        ladder=False,
        lvl=59,
        lvl_req=51,
    ),
    VISCERATUANT := _UniqueItem(
        value="xuc",
        ladder=False,
        lvl=36,
        lvl_req=28,
    ),
    MOSERS_BLESSED_CIRCLE := _UniqueItem(
        value="xml",
        ladder=False,
        lvl=39,
        lvl_req=31,
    ),
    STORMCHASER := _UniqueItem(
        value="xrg",
        ladder=False,
        lvl=43,
        lvl_req=35,
    ),
    TIAMATS_REBUKE := _UniqueItem(
        value="xit",
        ladder=False,
        lvl=46,
        lvl_req=38,
    ),
    GERKES_SANCTUARY := _UniqueItem(
        value="xow",
        ladder=False,
        lvl=52,
        lvl_req=44,
    ),
    RADAMENTS_SPHERE := _UniqueItem(
        value="xts",
        ladder=False,
        lvl=58,
        lvl_req=50,
    ),
    LIDLESS_WALL := _UniqueItem(
        value="xsh",
        ladder=False,
        lvl=49,
        lvl_req=41,
    ),
    LANCE_GUARD := _UniqueItem(
        value="xpk",
        ladder=False,
        lvl=43,
        lvl_req=35,
    ),
    VENOM_GRIP := _UniqueItem(
        value="xlg",
        ladder=False,
        lvl=37,
        lvl_req=29,
    ),
    GRAVEPALM := _UniqueItem(
        value="xvg",
        ladder=False,
        lvl=39,
        lvl_req=32,
    ),
    GHOULHIDE := _UniqueItem(
        value="xmg",
        ladder=False,
        lvl=44,
        lvl_req=36,
    ),
    LAVA_GOUT := _UniqueItem(
        value="xtg",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    HELLMOUTH := _UniqueItem(
        value="xhg",
        ladder=False,
        lvl=55,
        lvl_req=47,
    ),
    INFERNOSTRIDE := _UniqueItem(
        value="xlb",
        ladder=False,
        lvl=37,
        lvl_req=29,
    ),
    WATERWALK := _UniqueItem(
        value="xvb",
        ladder=False,
        lvl=40,
        lvl_req=32,
    ),
    SILKWEAVE := _UniqueItem(
        value="xmb",
        ladder=False,
        lvl=44,
        lvl_req=36,
    ),
    WAR_TRAVELER := _UniqueItem(
        value="xtb",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    GORE_RIDER := _UniqueItem(
        value="xhb",
        ladder=False,
        lvl=55,
        lvl_req=47,
    ),
    STRING_OF_EARS := _UniqueItem(
        value="zlb",
        ladder=False,
        lvl=37,
        lvl_req=29,
    ),
    RAZORTAIL := _UniqueItem(
        value="zvb",
        ladder=False,
        lvl=39,
        lvl_req=32,
    ),
    GLOOMS_TRAP := _UniqueItem(
        value="zmb",
        ladder=False,
        lvl=45,
        lvl_req=36,
    ),
    SNOWCLASH := _UniqueItem(
        value="ztb",
        ladder=False,
        lvl=49,
        lvl_req=42,
    ),
    THUNDERGODS_VIGOR := _UniqueItem(
        value="zhb",
        ladder=False,
        lvl=55,
        lvl_req=47,
    ),
    HARLEQUIN_CREST := _UniqueItem(
        value="uap",
        ladder=False,
        lvl=69,
        lvl_req=62,
    ),
    VEIL_OF_STEEL := _UniqueItem(
        value="uhm",
        ladder=False,
        lvl=77,
        lvl_req=73,
    ),
    THE_GLADIATORS_BANE := _UniqueItem(
        value="utu",
        ladder=False,
        lvl=85,
        lvl_req=85,
    ),
    ARKAINES_VALOR := _UniqueItem(
        value="upl",
        ladder=False,
        lvl=85,
        lvl_req=85,
    ),
    BLACKOAK_SHIELD := _UniqueItem(
        value="uml",
        ladder=False,
        lvl=67,
        lvl_req=61,
    ),
    STORMSHIELD := _UniqueItem(
        value="uit",
        ladder=False,
        lvl=77,
        lvl_req=73,
    ),
    HELLSLAYER := _UniqueItem(
        value="7bt",
        ladder=False,
        lvl=71,
        lvl_req=66,
    ),
    MESSERSCHMIDTS_REAVER := _UniqueItem(
        value="7ga",
        ladder=False,
        lvl=75,
        lvl_req=70,
    ),
    BARANARS_STAR := _UniqueItem(
        value="7mt",
        ladder=False,
        lvl=70,
        lvl_req=65,
    ),
    SCHAEFERS_HAMMER := _UniqueItem(
        value="7wh",
        ladder=False,
        lvl=83,
        lvl_req=79,
    ),
    THE_CRANIUM_BASHER := _UniqueItem(
        value="7gm",
        ladder=False,
        lvl=85,
        lvl_req=87,
    ),
    LIGHTSABRE := _UniqueItem(
        value="7cr",
        ladder=False,
        lvl=66,
        lvl_req=58,
    ),
    DOOMBRINGER := _UniqueItem(
        value="7b7",
        ladder=False,
        lvl=75,
        lvl_req=69,
    ),
    THE_GRANDFATHER := _UniqueItem(
        value="7gd",
        ladder=False,
        lvl=85,
        lvl_req=81,
    ),
    WIZARDSPIKE := _UniqueItem(
        value="7dg",
        ladder=False,
        lvl=69,
        lvl_req=61,
    ),
    CONSTRICTING_LOOP := _UniqueItem(
        value="rin",
        ladder=False,
        lvl=73,
        lvl_req=65,
    ),
    STORMSPIRE := _UniqueItem(
        value="7wc",
        ladder=False,
        lvl=78,
        lvl_req=70,
    ),
    EAGLEHORN := _UniqueItem(
        value="6l7",
        ladder=False,
        lvl=77,
        lvl_req=69,
    ),
    WINDFORCE := _UniqueItem(
        value="6lw",
        ladder=False,
        lvl=80,
        lvl_req=73,
    ),
    BUL_KATHOS_WEDDING_BAND := _UniqueItem(
        value="rin",
        ladder=False,
        lvl=66,
        lvl_req=58,
    ),
    THE_CATS_EYE := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=58,
        lvl_req=50,
    ),
    THE_RISING_SUN := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=73,
        lvl_req=65,
    ),
    CRESCENT_MOON := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=58,
        lvl_req=50,
    ),
    MARAS_KALEIDOSCOPE := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=80,
        lvl_req=67,
    ),
    ATMAS_SCARAB := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=60,
        lvl_req=60,
    ),
    DWARF_STAR := _UniqueItem(
        value="rin",
        ladder=False,
        lvl=53,
        lvl_req=45,
    ),
    RAVEN_FROST := _UniqueItem(
        value="rin",
        ladder=False,
        lvl=53,
        lvl_req=45,
    ),
    HIGHLORDS_WRATH := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=73,
        lvl_req=65,
    ),
    SARACENS_CHANCE := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=55,
        lvl_req=47,
    ),
    ARREATS_FACE := _UniqueItem(
        value="baa",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    HOMUNCULUS := _UniqueItem(
        value="nea",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    TITANS_REVENGE := _UniqueItem(
        value="ama",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    LYCANDERS_AIM := _UniqueItem(
        value="am7",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    LYCANDERS_FLANK := _UniqueItem(
        value="am9",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    THE_OCULUS := _UniqueItem(
        value="oba",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    HERALD_OF_ZAKARUM := _UniqueItem(
        value="pa9",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    BARTUCS_CUT_THROAT := _UniqueItem(
        value="9tw",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    JALALS_MANE := _UniqueItem(
        value="dra",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    THE_SCALPER := _UniqueItem(
        value="9ta",
        ladder=False,
        lvl=65,
        lvl_req=57,
    ),
    BLOODMOON := _UniqueItem(
        value="7sb",
        ladder=False,
        lvl=69,
        lvl_req=61,
    ),
    DJINN_SLAYER := _UniqueItem(
        value="7sm",
        ladder=False,
        lvl=73,
        lvl_req=65,
    ),
    DEATHBIT := _UniqueItem(
        value="9tk",
        ladder=False,
        lvl=52,
        lvl_req=44,
    ),
    WARSHRIKE := _UniqueItem(
        value="7bk",
        ladder=False,
        lvl=83,
        lvl_req=75,
    ),
    GUT_SIPHON := _UniqueItem(
        value="6rx",
        ladder=False,
        lvl=79,
        lvl_req=71,
    ),
    RAZORS_EDGE := _UniqueItem(
        value="7ha",
        ladder=False,
        lvl=75,
        lvl_req=67,
    ),
    DEMON_LIMB := _UniqueItem(
        value="7sp",
        ladder=False,
        lvl=71,
        lvl_req=63,
    ),
    STEEL_SHADE := _UniqueItem(
        value="ulm",
        ladder=False,
        lvl=70,
        lvl_req=62,
    ),
    TOMB_REAVER := _UniqueItem(
        value="7pa",
        ladder=False,
        lvl=86,
        lvl_req=84,
    ),
    DEATHS_WEB := _UniqueItem(
        value="7gw",
        ladder=False,
        lvl=74,
        lvl_req=66,
    ),
    NATURES_PEACE := _UniqueItem(
        value="rin",
        ladder=False,
        lvl=77,
        lvl_req=69,
    ),
    AZUREWRATH := _UniqueItem(
        value="7cr",
        ladder=False,
        lvl=87,
        lvl_req=85,
    ),
    SERAPHS_HYMN := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=73,
        lvl_req=65,
    ),
    FLESHRIPPER := _UniqueItem(
        value="7kr",
        ladder=False,
        lvl=76,
        lvl_req=68,
    ),
    ODIUM := _UniqueItem(
        value="7fb",
        ladder=False,
        lvl=87,
        lvl_req=80,
    ),
    HORIZONS_TORNADO := _UniqueItem(
        value="7fl",
        ladder=False,
        lvl=72,
        lvl_req=64,
    ),
    STONE_CRUSHER := _UniqueItem(
        value="7wh",
        ladder=False,
        lvl=76,
        lvl_req=68,
    ),
    JADE_TALON := _UniqueItem(
        value="7wb",
        ladder=False,
        lvl=74,
        lvl_req=66,
    ),
    SHADOW_DANCER := _UniqueItem(
        value="uhb",
        ladder=False,
        lvl=79,
        lvl_req=71,
    ),
    CEREBUS_BITE := _UniqueItem(
        value="drb",
        ladder=False,
        lvl=71,
        lvl_req=63,
    ),
    TYRAELS_MIGHT := _UniqueItem(
        value="uar",
        ladder=False,
        lvl=87,
        lvl_req=84,
    ),
    SOUL_DRAINER := _UniqueItem(
        value="umg",
        ladder=False,
        lvl=82,
        lvl_req=74,
    ),
    RUNE_MASTER := _UniqueItem(
        value="72a",
        ladder=False,
        lvl=80,
        lvl_req=72,
    ),
    DEATH_CLEAVER := _UniqueItem(
        value="7wa",
        ladder=False,
        lvl=78,
        lvl_req=70,
    ),
    EXECUTIONERS_JUSTICE := _UniqueItem(
        value="7gi",
        ladder=False,
        lvl=83,
        lvl_req=75,
    ),
    STONERAVEN := _UniqueItem(
        value="amd",
        ladder=False,
        lvl=72,
        lvl_req=64,
    ),
    LEVIATHAN := _UniqueItem(
        value="uld",
        ladder=False,
        lvl=73,
        lvl_req=65,
    ),
    WISP_PROJECTOR := _UniqueItem(
        value="rin",
        ladder=False,
        lvl=84,
        lvl_req=76,
    ),
    GARGOYLES_BITE := _UniqueItem(
        value="7ts",
        ladder=False,
        lvl=78,
        lvl_req=70,
    ),
    LACERATOR := _UniqueItem(
        value="7b8",
        ladder=False,
        lvl=76,
        lvl_req=68,
    ),
    MANG_SONGS_LESSON := _UniqueItem(
        value="6ws",
        ladder=False,
        lvl=86,
        lvl_req=82,
    ),
    VIPERFORK := _UniqueItem(
        value="7br",
        ladder=False,
        lvl=79,
        lvl_req=71,
    ),
    ETHEREAL_EDGE := _UniqueItem(
        value="7ba",
        ladder=False,
        lvl=82,
        lvl_req=74,
    ),
    DEMONHORNS_EDGE := _UniqueItem(
        value="bad",
        ladder=False,
        lvl=69,
        lvl_req=61,
    ),
    THE_REAPERS_TOLL := _UniqueItem(
        value="7s8",
        ladder=False,
        lvl=83,
        lvl_req=75,
    ),
    SPIRIT_KEEPER := _UniqueItem(
        value="drd",
        ladder=False,
        lvl=75,
        lvl_req=67,
    ),
    HELLRACK := _UniqueItem(
        value="6hx",
        ladder=False,
        lvl=84,
        lvl_req=76,
    ),
    ALMA_NEGRA := _UniqueItem(
        value="pac",
        ladder=False,
        lvl=85,
        lvl_req=77,
    ),
    DARKFORCE_SPAWN := _UniqueItem(
        value="nef",
        ladder=False,
        lvl=72,
        lvl_req=64,
    ),
    WIDOWMAKER := _UniqueItem(
        value="6sw",
        ladder=False,
        lvl=73,
        lvl_req=65,
    ),
    BLOOD_RAVENS_CHARGE := _UniqueItem(
        value="amb",
        ladder=False,
        lvl=79,
        lvl_req=71,
    ),
    GHOSTFLAME := _UniqueItem(
        value="7bl",
        ladder=False,
        lvl=70,
        lvl_req=62,
    ),
    SHADOW_KILLER := _UniqueItem(
        value="7cs",
        ladder=False,
        lvl=85,
        lvl_req=78,
    ),
    GIMMERSHRED := _UniqueItem(
        value="7ta",
        ladder=False,
        lvl=78,
        lvl_req=70,
    ),
    GRIFFONS_EYE := _UniqueItem(
        value="ci3",
        ladder=False,
        lvl=84,
        lvl_req=76,
    ),
    WINDHAMMER := _UniqueItem(
        value="7m7",
        ladder=False,
        lvl=76,
        lvl_req=68,
    ),
    THUNDERSTROKE := _UniqueItem(
        value="amf",
        ladder=False,
        lvl=77,
        lvl_req=69,
    ),
    DEMONS_ARCH := _UniqueItem(
        value="7s7",
        ladder=False,
        lvl=76,
        lvl_req=68,
    ),
    BONEFLAME := _UniqueItem(
        value="nee",
        ladder=False,
        lvl=80,
        lvl_req=72,
    ),
    STEEL_PILLAR := _UniqueItem(
        value="7p7",
        ladder=False,
        lvl=77,
        lvl_req=69,
    ),
    NIGHTWINGS_VEIL := _UniqueItem(
        value="uhm",
        ladder=False,
        lvl=75,
        lvl_req=67,
    ),
    CROWN_OF_AGES := _UniqueItem(
        value="urn",
        ladder=False,
        lvl=86,
        lvl_req=82,
    ),
    ANDARIELS_VISAGE := _UniqueItem(
        value="usk",
        ladder=False,
        lvl=85,
        lvl_req=83,
    ),
    DRAGONSCALE := _UniqueItem(
        value="pae",
        ladder=False,
        lvl=84,
        lvl_req=80,
    ),
    STEEL_CARAPACE := _UniqueItem(
        value="uul",
        ladder=False,
        lvl=74,
        lvl_req=66,
    ),
    MEDUSAS_GAZE := _UniqueItem(
        value="uow",
        ladder=False,
        lvl=84,
        lvl_req=76,
    ),
    RAVENLORE := _UniqueItem(
        value="dre",
        ladder=False,
        lvl=82,
        lvl_req=74,
    ),
    BONESHADE := _UniqueItem(
        value="7bw",
        ladder=False,
        lvl=84,
        lvl_req=79,
    ),
    FLAMEBELLOW := _UniqueItem(
        value="7gs",
        ladder=False,
        lvl=79,
        lvl_req=71,
    ),
    DEATHS_FATHOM := _UniqueItem(
        value="obf",
        ladder=False,
        lvl=81,
        lvl_req=73,
    ),
    WOLFHOWL := _UniqueItem(
        value="bac",
        ladder=False,
        lvl=85,
        lvl_req=79,
    ),
    SPIRIT_WARD := _UniqueItem(
        value="uts",
        ladder=False,
        lvl=76,
        lvl_req=68,
    ),
    KIRAS_GUARDIAN := _UniqueItem(
        value="ci2",
        ladder=False,
        lvl=85,
        lvl_req=77,
    ),
    ORMUS_ROBES := _UniqueItem(
        value="uui",
        ladder=False,
        lvl=83,
        lvl_req=75,
    ),
    GHEEDS_FORTUNE := _UniqueItem(
        value="cm3",
        ladder=False,
        lvl=70,
        lvl_req=62,
    ),
    STORMLASH := _UniqueItem(
        value="7fl",
        ladder=False,
        lvl=86,
        lvl_req=82,
    ),
    HALABERDS_REIGN := _UniqueItem(
        value="bae",
        ladder=False,
        lvl=85,
        lvl_req=77,
    ),
    SPIKE_THORN := _UniqueItem(
        value="upk",
        ladder=False,
        lvl=78,
        lvl_req=70,
    ),
    DRACULS_GRASP := _UniqueItem(
        value="uvg",
        ladder=False,
        lvl=84,
        lvl_req=76,
    ),
    FROSTWIND := _UniqueItem(
        value="7ls",
        ladder=False,
        lvl=78,
        lvl_req=70,
    ),
    TEMPLARS_MIGHT := _UniqueItem(
        value="uar",
        ladder=False,
        lvl=82,
        lvl_req=74,
    ),
    ESCHUTAS_TEMPER := _UniqueItem(
        value="obc",
        ladder=False,
        lvl=80,
        lvl_req=72,
    ),
    FIRELIZARDS_TALONS := _UniqueItem(
        value="7lw",
        ladder=False,
        lvl=75,
        lvl_req=67,
    ),
    SANDSTORM_TREK := _UniqueItem(
        value="uvb",
        ladder=False,
        lvl=72,
        lvl_req=64,
    ),
    MARROWWALK := _UniqueItem(
        value="umb",
        ladder=False,
        lvl=74,
        lvl_req=66,
    ),
    HEAVENS_LIGHT := _UniqueItem(
        value="7sc",
        ladder=False,
        lvl=69,
        lvl_req=61,
    ),
    MERMANS_SPROCKET := _UniqueItem(
        value="ulb",
        ladder=False,
        lvl=45,
        lvl_req=45,
    ),
    ARACHNID_MESH := _UniqueItem(
        value="ulc",
        ladder=False,
        lvl=87,
        lvl_req=80,
    ),
    NOSFERATUS_COIL := _UniqueItem(
        value="uvc",
        ladder=False,
        lvl=68,
        lvl_req=51,
    ),
    METALGRID := _UniqueItem(
        value="amu",
        ladder=False,
        lvl=85,
        lvl_req=81,
    ),
    VERDUNGOS_HEARTY_CORD := _UniqueItem(
        value="umc",
        ladder=False,
        lvl=71,
        lvl_req=63,
    ),
    SIGGARDS_STAUNCH := _UniqueItem(
        value="uhc",
        ladder=False,
        lvl=80,
        lvl_req=72,
    ),
    CARRION_WIND := _UniqueItem(
        value="rin",
        ladder=False,
        lvl=68,
        lvl_req=60,
    ),
    GIANT_SKULL := _UniqueItem(
        value="uh9",
        ladder=False,
        lvl=73,
        lvl_req=65,
    ),
    ASTREONS_IRON_WARD := _UniqueItem(
        value="7ws",
        ladder=False,
        lvl=68,
        lvl_req=60,
    ),
    ANNIHILUS := _UniqueItem(
        value="cm1",
        ladder=False,
        lvl=130,
        lvl_req=70,
    ),
    ARIOCS_NEEDLE := _UniqueItem(
        value="7sr",
        ladder=False,
        lvl=85,
        lvl_req=81,
    ),
    CRANEBEAK := _UniqueItem(
        value="7mp",
        ladder=False,
        lvl=71,
        lvl_req=63,
    ),
    NORDS_TENDERIZER := _UniqueItem(
        value="7cl",
        ladder=False,
        lvl=76,
        lvl_req=68,
    ),
    EARTH_SHIFTER := _UniqueItem(
        value="7gm",
        ladder=False,
        lvl=77,
        lvl_req=69,
    ),
    WRAITH_FLIGHT := _UniqueItem(
        value="7gl",
        ladder=False,
        lvl=84,
        lvl_req=76,
    ),
    BONEHEW := _UniqueItem(
        value="7o7",
        ladder=False,
        lvl=72,
        lvl_req=64,
    ),
    ONDALS_WISDOM := _UniqueItem(
        value="6cs",
        ladder=False,
        lvl=74,
        lvl_req=66,
    ),
    THE_REDEEMER := _UniqueItem(
        value="7sc",
        ladder=False,
        lvl=80,
        lvl_req=72,
    ),
    HEAD_HUNTERS_GLORY := _UniqueItem(
        value="ush",
        ladder=False,
        lvl=83,
        lvl_req=75,
    ),
    STEELREND := _UniqueItem(
        value="uhg",
        ladder=False,
        lvl=78,
        lvl_req=70,
    ),
    RAINBOW_FACET := _UniqueItem(
        value="jew",
        ladder=False,
        lvl=85,
        lvl_req=49,
    ),
    HELLFIRE_TORCH := _UniqueItem(
        value="cm2",
        ladder=False,
        lvl=120,
        lvl_req=75,
    ),
    ITHERAELS_PATH := _UniqueItem(
        value="utb",
        ladder=False,
        lvl=131,
        lvl_req=85,
    ),
    OVERLORDS_HELM := _UniqueItem(
        value="uhl",
        ladder=False,
        lvl=131,
        lvl_req=85,
    ),
    DARK_ABYSS := _UniqueItem(
        value="uth",
        ladder=False,
        lvl=131,
        lvl_req=85,
    ),
    AIDANS_SCAR := _UniqueItem(
        value="7qr",
        ladder=False,
        lvl=131,
        lvl_req=85,
    ),
    HADRIELS_HAND := _UniqueItem(
        value="7bs",
        ladder=False,
        lvl=131,
        lvl_req=85,
    ),
    TRUE_SILVER := _UniqueItem(
        value="am5",
        ladder=False,
        lvl=24,
        lvl_req=20,
    ),
    QUETZALCOATL := _UniqueItem(
        value="dr2",
        ladder=False,
        lvl=35,
        lvl_req=29,
    ),
    CYCLOPEAN_ROAR := _UniqueItem(
        value="ba6",
        ladder=False,
        lvl=34,
        lvl_req=28,
    ),
    SANKEKURS_FALL := _UniqueItem(
        value="pa3",
        ladder=False,
        lvl=37,
        lvl_req=29,
    ),
    MAGE_SLAYER := _UniqueItem(
        value="9ar",
        ladder=False,
        lvl=32,
        lvl_req=27,
    ),
    KALANS_LEGACY := _UniqueItem(
        value="ne6",
        ladder=False,
        lvl=30,
        lvl_req=26,
    ),
    TEMPEST := _UniqueItem(
        value="ob6",
        ladder=False,
        lvl=28,
        lvl_req=25,
    ),
    BAND_OF_SKULLS := _UniqueItem(
        value="rbe",
        ladder=False,
        lvl=131,
        lvl_req=90,
    ),
    CAGE_OF_THE_UNSULLIED := _UniqueItem(
        value="rar",
        ladder=False,
        lvl=131,
        lvl_req=90,
    ),
    THE_THIRD_EYE := _UniqueItem(
        value="ram",
        ladder=False,
        lvl=131,
        lvl_req=90,
    ),
    ZERAES_RESOLVE := _UniqueItem(
        value="ame",
        ladder=False,
        lvl=87,
        lvl_req=76,
    ),
    OCCULTIST := _UniqueItem(
        value="utg",
        ladder=False,
        lvl=87,
        lvl_req=70,
    ),
    BRIMSTONE_RAIN := _UniqueItem(
        value="6bs",
        ladder=False,
        lvl=87,
        lvl_req=80,
    ),
    AKARATS_DEVOTION := _UniqueItem(
        value="7qs",
        ladder=False,
        lvl=87,
        lvl_req=74,
    ),
    MARTYRDOM := _UniqueItem(
        value="ned",
        ladder=False,
        lvl=87,
        lvl_req=68,
    ),
    STALKERS_CULL := _UniqueItem(
        value="7tw",
        ladder=False,
        lvl=87,
        lvl_req=65,
    ),
    PURGATORY := _UniqueItem(
        value="utp",
        ladder=False,
        lvl=87,
        lvl_req=75,
    ),
    RAEKORS_VIRTUE := _UniqueItem(
        value="baf",
        ladder=False,
        lvl=87,
        lvl_req=78,
    ),
    URSAS_NIGHTMARE := _UniqueItem(
        value="drf",
        ladder=False,
        lvl=50,
        lvl_req=42,
    ),
    ZHARS_SANCTUM := _UniqueItem(
        value="t51",
        ladder=False,
        lvl=80,
        lvl_req=80,
    ),
    WARLORD_OF_BLOOD := _UniqueItem(
        value="t52",
        ladder=False,
        lvl=80,
        lvl_req=80,
    ),
    FALLEN_GARDENS := _UniqueItem(
        value="t53",
        ladder=False,
        lvl=80,
        lvl_req=80,
    ),
    ULDYSSIANS_AWAKENING := _UniqueItem(
        value="7st",
        ladder=False,
        lvl=80,
        lvl_req=74,
    ),
    LEORICS_MITHRIL_BANE := _UniqueItem(
        value="7cm",
        ladder=False,
        lvl=78,
        lvl_req=68,
    ),
    TWILIGHTS_REFLECTION := _UniqueItem(
        value="urg",
        ladder=False,
        lvl=18,
        lvl_req=13,
    ),
    WRAITHSKIN := _UniqueItem(
        value="ung",
        ladder=False,
        lvl=61,
        lvl_req=53,
    ),
    TITANS_GRIP := _UniqueItem(
        value="ulg",
        ladder=False,
        lvl=45,
        lvl_req=38,
    ),
    SHATTERBLADE := _UniqueItem(
        value="7di",
        ladder=False,
        lvl=73,
        lvl_req=65,
    ),
    DENMOTHER := _UniqueItem(
        value="drc",
        ladder=False,
        lvl=66,
        lvl_req=58,
    ),
    EBONBANE := _UniqueItem(
        value="amc",
        ladder=False,
        lvl=70,
        lvl_req=63,
    ),
    WHISPERING_MIRAGE := _UniqueItem(
        value="7xf",
        ladder=False,
        lvl=76,
        lvl_req=68,
    ),
    SKYWARDEN := _UniqueItem(
        value="paf",
        ladder=False,
        lvl=85,
        lvl_req=77,
    ),
    SKORN := _UniqueItem(
        value="ob7",
        ladder=False,
        lvl=36,
        lvl_req=27,
    ),
    ACHILLES_STRIKE := _UniqueItem(
        value="9b8",
        ladder=False,
        lvl=59,
        lvl_req=51,
    ),
    WILDSPEAKER := _UniqueItem(
        value="ba7",
        ladder=False,
        lvl=52,
        lvl_req=44,
    ),
    FENRIS := _UniqueItem(
        value="dr6",
        ladder=False,
        lvl=48,
        lvl_req=40,
    ),
    SACRED_TOTEM := _UniqueItem(
        value="neg",
        ladder=False,
        lvl=72,
        lvl_req=64,
    ),
    IMPERIAL_PALACE := _UniqueItem(
        value="t54",
        ladder=False,
        lvl=80,
        lvl_req=80,
    ),
    OUTER_VOID := _UniqueItem(
        value="t55",
        ladder=False,
        lvl=80,
        lvl_req=80,
    ),
    BALEFIRE := _UniqueItem(
        value="aqv",
        ladder=False,
        lvl=14,
        lvl_req=14,
    ),
    SWIFTWIND_NEEDLE := _UniqueItem(
        value="aqv2",
        ladder=False,
        lvl=32,
        lvl_req=32,
    ),
    TOMBSONG := _UniqueItem(
        value="aqv2",
        ladder=False,
        lvl=36,
        lvl_req=36,
    ),
    AETHERWING := _UniqueItem(
        value="aqv3",
        ladder=False,
        lvl=55,
        lvl_req=55,
    ),
    BASILISKS_QUILL := _UniqueItem(
        value="aqv3",
        ladder=False,
        lvl=62,
        lvl_req=62,
    ),
    DOOMS_FINGER := _UniqueItem(
        value="aqv3",
        ladder=False,
        lvl=87,
        lvl_req=68,
    ),
    RAMFODDER := _UniqueItem(
        value="cqv",
        ladder=False,
        lvl=8,
        lvl_req=8,
    ),
    ANVILGUARD_STRAP := _UniqueItem(
        value="cqv2",
        ladder=False,
        lvl=34,
        lvl_req=34,
    ),
    SHATTERHEAD := _UniqueItem(
        value="cqv2",
        ladder=False,
        lvl=47,
        lvl_req=47,
    ),
    ABYSSAL_WARD := _UniqueItem(
        value="cqv3",
        ladder=False,
        lvl=60,
        lvl_req=60,
    ),
    BANNERLORDS_CALL := _UniqueItem(
        value="cqv3",
        ladder=False,
        lvl=60,
        lvl_req=65,
    ),
    FROZEN_SORROW := _UniqueItem(
        value="cqv3",
        ladder=False,
        lvl=87,
        lvl_req=72,
    ),
    CRACKLESHOT := _UniqueItem(
        value="6hb",
        ladder=False,
        lvl=87,
        lvl_req=72,
    ),
    CITY_OF_UREH := _UniqueItem(
        value="t56",
        ladder=False,
        lvl=80,
        lvl_req=80,
    ),
]
